baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Honkworks'

[params]
  cdnBaseURL = "https://assets.honkworks.net/"
  cdnLocalAssetPrefix = "/cdn-assets/"

[module]
    [[module.imports]]
        path = "github.com/nicokaiser/hugo-theme-gallery/v4"