baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Honkworks'
theme = 'Gallery'

[params]
  imageBaseURL = "https://assets.honkworks.net"

[module]
    [[module.imports]]
        path = "github.com/nicokaiser/hugo-theme-gallery/v4"